DROP TABLE NOMINAS;
DROP TABLE EMPLEADOS;

CREATE TABLE EMPLEADOS (
NOMBRE VARCHAR(50) not null,
DNI VARCHAR(9) not null,
SEXO CHAR not null,
CATEGORIA NUMBER not null,
ANYOS NUMBER not null,
PRIMARY KEY (DNI)
);

CREATE TABLE NOMINAS (
DNI VARCHAR(9) not null,  
SUELDO NUMBER not null,
PRIMARY KEY (DNI),
CONSTRAINT FK_DNI FOREIGN KEY(DNI) REFERENCES EMPLEADOS(DNI) ON DELETE CASCADE
);

INSERT INTO EMPLEADOS VALUES('James Cosling','48811600B','M','4 ','7');
INSERT INTO EMPLEADOS VALUES('Ada Lovealace','48814047C','F','1 ','0');
INSERT INTO EMPLEADOS VALUES('Joe Biden','28251761X','M','2 ','5');

INSERT INTO NOMINAS VALUES('48811600B',145000);
INSERT INTO NOMINAS VALUES('48814047C',50000);
INSERT INTO NOMINAS VALUES('28251761X',95000);